server:
  port: 8888
  servlet.context-path: /

logging:
  level:
    com.consul.docker.healthcheck: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%logger{45}] %msg%n"

consul:
#  address: 192.168.114.131:8500,192.168.114.132:8500,192.168.114.133:8500
#  token: 7824be38-f753-3e6e-ae50-1bb1a3a1fe4b
  address: 10.135.140.12:8500,10.135.140.13:8500,10.135.140.14:8500
  token: 6545f267-d97d-4824-9ff0-d0a7793a9e5e

zookeeper:
  url: 10.135.140.12:21810,10.135.140.13:21810,10.135.140.14:21810
  bashPath: /wade-relax
  app:
    groupname: base,itf,flow

healthcheck:
  initialDelay: 10000
  fixedRate: 5000
  retryCount: 3
  web:
    prefix: crm-web
  app:
    prefix: crm-app
  root:
    # 上下文为 "/" 的模块，可以配置多个，例如: ngboss,touchframe
    context: ngboss
